title: MotivAcção
description: >- # this means to ignore newlines until "baseurl:"
  Carga Motivacional
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://cargamotivacional.com" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-analytics
  - jekyll-paginate-v2

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

sass:
  sass_dir: assets/_sass
  style: compressed

image: /assets/img/logobranco.svg

pagination:
  enabled: true
  per_page: 10
  limit: 0
  sort_field: 'date'
  sort_reverse: true
  trail: 
    before: 2
    after: 2

jekyll_analytics:
  GoogleAnalytics:          # Add, if you want to track with Google Analytics
    id: ca-pub-5935260290806776          # Required - replace with your tracking id
    anonymizeIp: false      # Optional - Default: false - set to true for anonymized tracking
