backend:
  name: git-gateway
  use_large_media_transforms_in_media_library: false

media_folder: 'assets/uploads'

logo_url: 'https://izitech.co/assets/img/IZIlogo.svg'

collections:
  - label: "Posts"
    name: "posts"
    folder: _posts
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Titulo", name: "title", widget: "string"}
      - {label: "Data", name: "date", widget: "datetime"}
      - label: "Categorias"
        name: "category"
        widget: "list"
        options: ["Empreendedores", "Saude", "Pessoal"]
      - {label: "Tag", name: "tag", widget: "string"}
      - {label: "Imagem", name: "image", widget: "image"}
      - {label: "Layout", name: "layout", default: "post", widget: "hidden"}
      - {label: "Corpo", name: "body", widget: "markdown"}